### ISSUE TITLE
Nested case splitting doesn't work

### ISSUE THREAD

**Issue by L7R7** [rikvdkleij/intellij-haskell#610]
![image](https://user-images.githubusercontent.com/16477399/93930991-80349f80-fd1e-11ea-8360-02f7df196029.png)

I was hoping for the case split to work on the `Bool` inside the newtype resulting in 

```hs
foo :: Bar -> String
foo (Bar True) = ""
foo (Bar False) = ""
```

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Because the `Bool` is not explicitly defined in type signature of `foo` the current implementation does not work for this case. Will take a look how to fix this soon.

**Comment by mbwgh** [comment]
But that is probably not the only criterion, right?

For instance, I can't seem to trigger the case split intention for
```haskell
bla :: Maybe Int -> IO ()
bla m = undefined
```
either.

**Comment by rikvdkleij** [comment]
@mbwgh Thanks for reporting!

That should work. Have to fix that.

**Comment by rikvdkleij** [comment]
@mbwgh Should be fixed in next release.

**Comment by rikvdkleij** [comment]
@mbwgh Fixed in beta84 which is uploaded to alpha plugin repo.

**Comment by mbwgh** [comment]
That's great news!

I wanted to try it out right away actually, but it appears that the alpha repo now has beta83 as latest version.

**Comment by rikvdkleij** [comment]
Jetbrains first has to approve this version before it’s available.
You can also download the plugin from Releases, https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta84

**Comment by mbwgh** [comment]
I was able to try it out and found two issues.
* Type synonyms are not resolved. For instance, there is no option to case-split on `String`, but it works on `[Char]`.
* You can now case-split on `Char` and `Int` and so on. Maybe this makes sense when the constructors are actually available, but probably not in general.

![2020-11-03-064421_371x131_scrot](https://user-images.githubusercontent.com/28275377/97953832-f9092b80-1da1-11eb-9256-d033097a3117.png)

**Comment by rikvdkleij** [comment]
>  For instance, there is no option to case-split on String

Hmm, don't understand. Why do you want to case split on a String?
It works on `[Char]` because it's a List.

**Comment by rikvdkleij** [comment]
Thanks for your feedback!

> Type synonyms are not resolved. For instance, there is no option to case-split on String, but it works on [Char].

Yes, type synonyms are not resolved. I wonder if I should put effort into that.

> Maybe this makes sense when the constructors are actually available, but probably not in general.

Yeah okay but it doesn't hurt 😄  Otherwise I have to make an exception.
